version: '3.8'

services:
  reserveatdatabase:
    build:
      context: .
      dockerfile: docker/DockerFile
    ports:
      - "5433:5432"
    networks:
      - app
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app:


volumes:
  pgdata: